Repository turbot/steampipe, pull requests merged in 2021-03, with the labels that each got.

#244 wrap `plugin list` output to window width. Closes #235
  cmd/plugin.go
  db/client_execute.go
  db/interactive_client.go
  db/query.go
  definitions/results/queryresult.go
  definitions/results/resultstreamer.go
  display/display.go
  metaquery/handlers.go
Labels: enhancement

#237 `plugin update` refactoring. Closes #216. Closes #234
  cmd/plugin.go
  connection_config/connection_validation.go
  plugin/actions.go
  plugin/versionchecker.go
  task/pluginversioncheck.go
  utils/useragent.go
Labels: bug

#240 error message. Closes #118
  cmd/plugin.go
  cmd/query.go
  cmd/service.go
  db/interactive_client.go
  utils/errors.go
Labels: enhancement

#245 `steampipe` server not found. Closes #220
  connection_config/connection_validation.go
  db/connections.go
Labels: bug

#258 formatting consistency. Closes #257
  metaquery/handlers.go
Labels: enhancement

#269 odd update notification. Closes #265
  plugin/versionchecker.go
Labels: ui

#280 Move log location. Closes #278
  constants/config.go
  db/start.go
Labels: enhancement

#256 work with the default viper instance. Closes #243
  cmd/root.go
  cmd/service.go
  cmdconfig/builder.go
  cmdconfig/cmd_flags.go
  cmdconfig/viper.go
  db/interactive_client.go
  display/display.go
  go.mod
Labels: enhancement

#284 Add argument to specify location of the .steampipe folder. Closes #241
  cmd/root.go
  cmdconfig/viper.go
  constants/args.go
  constants/config.go
  db/start.go
  db/stop.go
Labels: enhancement

#296 update-check should read off of config file. Closes #293
  cmd/root.go
  cmdconfig/builder.go
  constants/env.go
  main.go
  utils/debugdump.go
  utils/json.go
Labels: enhancement

#298 Create default options file. Closes #279
  constants/defaultspc.go
  steampipeconfig/load.go
Labels: enhancement

#308 `plugin install` and `plugin update` take a long time to shutdown the service. Closes #305
  cmd/plugin.go
Labels: bug

#314 Bump Go to 1.16
  .github/workflows/buildDBImage.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  go.mod
Labels: house-keeping

#315 `.header` with `table` output. Closes #312
  display/display.go
Labels: bug

#325 ensure `steampipe` fdw server. Closes #324
  db/start.go
Labels: bug

#331 fixes issue where `service` is always listening on `network`. Closes #330
  cmdconfig/deprecate.go
Labels: bug

#327 Increase coverage of acceptance tests. Closes #323
  .github/workflows/test.yml
  db/install.go
  tests/acceptance/run.sh
  tests/acceptance/test_data/templates/expected_query_csv.csv
  tests/acceptance/test_data/templates/expected_query_csv_header_off.csv
  tests/acceptance/test_data/templates/expected_query_json.json
  tests/acceptance/test_data/templates/expected_query_line.txt
  tests/acceptance/test_data/templates/expected_query_table_header_off.txt
  tests/acceptance/test_data/templates/expected_service_start_listen_local.txt
  tests/acceptance/test_data/templates/expected_service_start_port.txt
  tests/acceptance/test_files/001.install.bats
  tests/acceptance/test_files/001.query.bats
  tests/acceptance/test_files/002.service.bats
  tests/acceptance/test_files/003.plugin.bats
  tests/acceptance/test_files/004.query.bats
  tests/acceptance/test_files/005.chaos.bats
Labels: devops

#334 manually dispatched - automated release. Closes #333
  .github/workflows/release.yml
Labels: devops

#337 fix json encoding issues. Closes #336
  display/column.go
  display/display.go
  tests/acceptance/test_data/templates/expected_6.json
  tests/acceptance/test_files/004.query.bats
Labels: bug

#335 fix extra trailing white-space issue in `line` output. Closes #332
  display/display.go
  tests/acceptance/test_data/templates/expected_line_long.txt
  tests/acceptance/test_files/004.query.bats
Labels: bug

#277 `plugin update` and `plugin install` display refactor. Closes #274
  cmd/plugin.go
  display/installreport.go
Labels: ui
