Repository turbot/steampipe, pull requests merged in 2021-11, with the labels that each got.

#1063 Constrain `table` rendering to a minimum width. Closes #1062
  cmd/check.go
  control/controldisplay/formatter_text.go
  control/controldisplay/group.go
  control/controldisplay/group_counter.go
  control/controldisplay/group_counter_graph.go
  control/controldisplay/group_heading.go
  control/controldisplay/group_title.go
  control/controldisplay/range.go
  control/controldisplay/severity.go
  control/controldisplay/spacer.go
  control/controldisplay/table.go
  control/controldisplay/table_test.go
Labels: enhancement

#1060 add generic queries and controls to simulate control rendering(outputs/exports) acceptance tests. closes #1059
  cmdconfig/viper.go
  constants/args.go
  constants/env.go
  control/controldisplay/formatter_text.go
  tests/acceptance/run.sh
  tests/acceptance/test_data/control_rendering_test_mod/mod.sp
  tests/acceptance/test_data/control_rendering_test_mod/query/gen_query.sp
  tests/acceptance/test_data/control_rendering_test_mod/query/gen_query.sql
  tests/acceptance/test_data/control_rendering_test_mod/query/long_short_unicode_reasons.sql
  tests/acceptance/test_data/control_rendering_test_mod/sp_check_test/control_check_rendering.sp
  tests/acceptance/test_data/control_rendering_test_mod/sp_check_test/control_reasons_titles.sp
  tests/acceptance/test_data/templates/expected_all_alarm.txt
  tests/acceptance/test_data/templates/expected_check_csv.csv
  tests/acceptance/test_data/templates/expected_check_csv_noheader.csv
  tests/acceptance/test_data/templates/expected_check_html.html
  tests/acceptance/test_data/templates/expected_check_json.json
  tests/acceptance/test_data/templates/expected_check_markdown.md
  tests/acceptance/test_data/templates/expected_long_title.txt
  tests/acceptance/test_data/templates/expected_mixed_results.txt
  tests/acceptance/test_data/templates/expected_reasons.txt
  tests/acceptance/test_data/templates/expected_short_title.txt
  tests/acceptance/test_data/templates/expected_unicode_title.txt
  tests/acceptance/test_files/008.check.bats
Labels: house-keeping, test

#1086 Fixes issue where documentation link was missing after a non-turbot plugin was installed. closes #1075
  cmd/plugin.go
Labels: enhancement

#1066 validate database name if `STEAMPIPE_INITDB_DATABASE_NAME` is used. Closes #1065
  db/db_local/install.go
  tests/acceptance/test_files/002.service.bats
Labels: bug

#1105 Fixes issue where connection with `CamelCase` names were not getting removed from the service. Closes #1074
  db/db_local/local_db_client_connections.go
Labels: bug

#1098 Add support for quoted arguments with whitespace in `.<metacmd>`. Closes #1067
  query/metaquery/completers.go
  query/metaquery/definitions.go
  query/metaquery/handlers.go
  query/metaquery/utils.go
  query/metaquery/utils_test.go
  query/metaquery/validators.go
Labels: enhancement

#1100 Add support to fall back to `more` (if available) - where `less` is not available in the environment. Closes #1072
  display/pager.go
Labels: enhancement

#1099 Fix issue where pg `usernames` weren't getting escaped properly when setting `search path`. Closes 1094. Closes 1082.
  db/db_local/local_db_client.go
Labels: bug

#937 Support Linux package managers(apt-get, yum, snap). Closes #595
  .github/workflows/release.yml
  .gitignore
  .goreleaser.yml
Labels: enhancement, installation

#1123 Optimize parallel control execution. Closes #1101
  cmd/check.go
  cmd/query.go
  constants/control_execute.go
  constants/db.go
  constants/postgresql_conf.go
  control/controlexecute/control_run.go
  control/controlexecute/execution_tree.go
  control/controlexecute/progress.go
  control/controlexecute/result_group.go
  db/db_client/db_client.go
  db/db_client/db_client_execute.go
  db/db_client/db_client_session.go
  db/db_client/session_stat.go
  db/db_common/backend_pid.go
  db/db_common/client.go
  db/db_common/db_session.go
  db/db_common/introspection_tables.go
  db/db_common/prepared_statements.go
  db/db_local/local_db_client.go
  utils/lifecycle_timer.go
  workspace/session_data.go
Labels: enhancement

#1135 When running as `root` steampipe should error out with a `non-zero` exit-code . Closes #1114
  main.go
Labels: bug

#1143 Fix issue where `check` progress report `<0` running when facing errors. Closes #1131
  cmd/check.go
  control/controlexecute/control_run.go
  control/controlexecute/progress.go
  display/spinner.go
Labels: bug

#1147 Plugin Manager state tied to DBService state
  cmd/service.go
  db/db_local/create_client.go
  db/db_local/install.go
  db/db_local/service.go
  db/db_local/start_services.go
  db/db_local/stop_services.go
  plugin_manager/lifecycle.go
  plugin_manager/plugin_manager_client.go
  plugin_manager/state.go
  utils/errors.go
Labels: bug

#1161 Update goreleaser to build binary for Mac M1. Closes #1160
  .goreleaser.yml
Labels: enhancement

#1173 Fixes issue where a `check` cancel was not waiting for query cancellation to finish. Closes #1171
  constants/control_execute.go
  control/controlexecute/execution_tree.go
Labels: bug, controls

#1190 enable dynamic schema tests. Closes #1076
  tests/acceptance/test_data/csv_plugin_test/a.csv
  tests/acceptance/test_files/018.dynamic-schema.bats
Labels: test

#1178 show `Time` at the end of the query results when `timing:ON`. closes #1177
  display/display.go
Labels: enhancement

#1188 Fixes issue where `local` plugins are not evaluated as `local` as given in docs. Closes #1176
  steampipeconfig/parse/connection.go
Labels: bug
