Repository turbot/steampipe, pull requests merged in 2021-12, with the labels that each got.

#1213 Add `context` awareness in services and `cmd`s. Closes #1206. Closes #1214. Closes #1215
  cmd/check.go
  cmd/plugin.go
  cmd/query.go
  cmd/report.go
  cmd/service.go
  connection_watcher/connection_watcher.go
  control/controlexecute/control_run.go
  db/db_client/db_client.go
  db/db_client/db_client_cache_control.go
  db/db_client/db_client_search_path.go
  db/db_common/client.go
  db/db_common/wait_connection.go
  db/db_local/create_client.go
  db/db_local/execute.go
  db/db_local/functions.go
  db/db_local/install.go
  db/db_local/local_db_client.go
  db/db_local/local_db_client_connections.go
  db/db_local/refresh_connections.go
  db/db_local/start_services.go
  db/db_local/stop_services.go
  interactive/interactive_client.go
  interactive/run.go
  ociinstaller/db.go
  ociinstaller/fdw.go
  ociinstaller/ocidownloader.go
  ociinstaller/plugin.go
  ociinstaller/steampipeimage.go
  plugin/actions.go
  query/metaquery/handlers.go
  report/reportserver/api.go
  report/reportserver/server.go
Labels: house-keeping

#1219 `github.com/jackc/pgx` driver for postgres. Closes #1179
  db/db_client/db_client.go
  db/db_client/db_client_session.go
  db/db_common/backend_pid.go
  db/db_common/db_session.go
  db/db_local/create_client.go
  db/db_local/install.go
  db/db_local/local_db_client.go
  go.mod
  go.sum
  main.go
  tests/acceptance/test_data/templates/expected_6.json
Labels: devops, house-keeping, optimization, service

#1181 Improve plugin uninstall output when connections remain. Closes #1158
  cmd/plugin.go
  plugin/actions.go
  utils/plural.go
Labels: enhancement

#1228 Fix issue where 'check' was not reusing database connections for cloud runs. Closes #1227
  control/controlexecute/control_run.go
  db/db_common/prepared_statements.go
Labels: bug

#1234 Fix issue where control from interactive autocomplete is not executing. Closes #1233
  interactive/interactive_client.go
Labels: bug

#1247 Fix issue where unqualified table names are not showing up in autocomplete. Closes #1245
  db/db_client/db_client.go
Labels: bug

#1243 Fix issue where interactive prompt hangs if query is executed before init. Closes #1242
  interactive/interactive_client.go
  interactive/interactive_client_init.go
Labels: bug

#1260 Fix issue where service is not shutdown when check is cancelled. Closes #1250
  cmd/check.go
  cmd/query.go
  cmd/service.go
  control/controlexecute/control_run.go
  control/controlexecute/result_group.go
  db/db_client/db_client.go
  db/db_client/db_client_execute.go
  db/db_client/db_client_session.go
  db/db_common/db_session.go
  db/db_local/local_db_client.go
  db/db_local/stop_services.go
  main.go
  runtime_constants/execution_id.go
  runtime_constants/runtime_constants.go
  utils/debugdump.go
Labels: bug
