Repository turbot/steampipe, pull requests merged in 2021-08, with the labels that each got.

#702 Add support for controlling the `fdw` cache from the `interactive` prompt. Closes #688
  constants/args.go
  constants/commands.go
  constants/db.go
  db/db_common/db_client.go
  db/local_db/functions.go
  db/local_db/install.go
  db/local_db/local_client.go
  db/local_db/local_client_cache_control.go
  db/local_db/local_client_connections.go
  db/local_db/query.go
  db/local_db/start_database.go
  go.sum
  interactive/interactive_client.go
  query/metaquery/definitions.go
  query/metaquery/handlers.go
Labels: enhancement

#732 Add support for syntax highlighting in `interactive prompt`. Closes #64
  go.mod
  go.sum
  interactive/highlighter.go
  interactive/interactive_client.go
Labels: enhancement

#737 Add acceptance tests for "search path not being honored by `steampipe check`". Closes #721
  tests/acceptance/test_data/sample_workspace/cis_v130/search_path.sp
  tests/acceptance/test_data/sample_workspace/query/search_path_1.sql
  tests/acceptance/test_data/sample_workspace/query/search_path_2.sql
  tests/acceptance/test_data/templates/expected_check_json.json
  tests/acceptance/test_files/008.check.bats
  tests/acceptance/test_files/009.check-search-path.bats
Labels: test

#748 `service stop` should not trigger daily checks and tasks. Closes #745
  task/runner.go
  tests/acceptance/test_files/002.service.bats
Labels: house-keeping

#747 Add acceptance test for "When an aggregator connection is evaluating a wildcard, only include connections with compatible type". Closes #720
  tests/acceptance/test_data/source_files/aggregator.spc
  tests/acceptance/test_files/010.connection.bats
Labels: test

#738 Fix for spinner not getting shown if interactive prompt is waiting for `init` to finish before query. Closes #671
  interactive/interactive_client.go
Labels: bug

#741 Fix issue where `prompt` disappears if any messages are shown. Closes #713
  db/db_common/workspace_resource_provider.go
  go.mod
  go.sum
  interactive/interactive_client.go
  interactive/interactive_client_init.go
  report/reportserver/server.go
  workspace/workspace.go
  workspace/workspace_events.go
Labels: bug

#763 Fix for `0` exit code even if `service start` fails. Closes #762
  cmd/service.go
Labels: bug

#761 Fix for failing acceptance tests. Closes #756
  tests/acceptance/test_files/002.service.bats
  tests/acceptance/test_files/004.query.bats
  tests/acceptance/test_files/005.chaos.bats
  tests/acceptance/test_files/006.search-path.bats
  tests/acceptance/test_files/007.matrix.bats
  tests/acceptance/test_files/008.check.bats
  tests/acceptance/test_files/009.check-search-path.bats
  tests/acceptance/test_files/010.connection.bats
Labels: house-keeping

#765 Fix for missing `control description`, `control_title` in `csv` output of `check` command. Closes #739
  .github/workflows/test.yml
  control/controldisplay/csv.go
  control/controldisplay/formatter_test.go
  control/controldisplay/result_columns.go
  control/controlexecute/result_row.go
  go.mod
  report/reportexecute/panel_run.go
  report/reportexecute/report_run.go
  tests/acceptance/test_data/templates/expected_check_csv.csv
  tests/acceptance/test_data/templates/expected_check_csv_noheader.csv
  tests/acceptance/test_data/templates/expected_check_separator_csv.csv
Labels: bug, enhancement

#789 Fix for disappearing prompt after init updates `fdw` in `interactive mode`. Closes #785
  interactive/interactive_client.go
Labels: bug

#784 Add more acceptance tests for aggregated connections. Closes #783
  tests/acceptance/test_data/templates/expected_aggregated_result.json
  tests/acceptance/test_files/010.connection.bats
Labels: test

#781 Add acceptance tests for cache functionality. Closes #780
  tests/acceptance/test_data/sample_workspace/cis_v130/cache.sp
  tests/acceptance/test_data/sample_workspace/query/check_cache.sql
  tests/acceptance/test_files/012.cache.bats
Labels: test

#779 Handle `context canceled` error during control runs. Closes #757
  constants/db.go
  constants/errors.go
  constants/workspace.go
  control/controlexecute/control_run.go
  tests/acceptance/test_data/sample_workspace/cis_v130/plugin_crash.sp
  tests/acceptance/test_data/sample_workspace/query/check_plugincrash_normalquery1.sql
  tests/acceptance/test_data/sample_workspace/query/check_plugincrash_normalquery2.sql
  tests/acceptance/test_files/011.check-plugin-crash.bats
Labels: bug

#794 Modify the queries in search-path acceptance tests. Closes #793
  tests/acceptance/test_data/sample_workspace/query/search_path_1.sql
  tests/acceptance/test_data/sample_workspace/query/search_path_2.sql
Labels: test

#792 Modify acceptance tests for aggregated connections. Closes #750
  tests/acceptance/test_data/templates/expected_aggregated_result.json
  tests/acceptance/test_files/010.connection.bats
Labels: test

#795 Persist syntax highlighting after query is executed. Closes #746
  go.mod
  go.sum
  interactive/highlighter.go
  interactive/interactive_client.go
Labels: enhancement

#799 Fix for `Error: context cancelled` message on `Ctrl+C`. Closes #786
  utils/errors.go
Labels: house-keeping

#798 Fix for delayed spinner start in interactive mode.
  db/local_db/local_client_execute.go
Labels: bug

#809 Add support for logging process output if `initdb` fails. Closes #800
  db/local_db/install.go
Labels: enhancement

#807 Add `dependabot` config. Closes #806
  .github/dependabot.yml
Labels: house-keeping

#805 Adaptive suggestion window instead of `console window is too small`. Closes #712
  go.mod
  go.sum
Labels: enhancement

#817 Fix issue with `dependabot.yml` config. Closes #816
  .github/dependabot.yml
  .github/workflows/test.yml
Labels: house-keeping
