Repository turbot/steampipe, pull requests merged in 2021-09, with the labels that each got.

#824 Force stopping service should not be required during initdb. Closes #615
  db/local_db/install.go
Labels: house-keeping

#841 Cache build and test dependencies in acceptance test workflow. Closes #801
  .github/workflows/test.yml
Labels: house-keeping

#825 Output service logs in `TRACE` while service is starting. Closes #810
  db/local_db/start_database.go
Labels: house-keeping

#808 `bash`/`zsh` completion. Closes #481
  cmd/check.go
  cmd/completion.go
  cmd/query.go
  cmd/root.go
  go.mod
  go.sum
  steampipeconfig/modconfig/workspace_resources.go
  task/runner.go
Labels: enhancement

#851 Fix for history persistence of empty strings. Closes #850
  interactive/interactive_client.go
  query/queryhistory/history.go
Labels: bug

#862 Update `shell` completion cmd help text.
  cmd/completion.go
Labels: house-keeping

#891 Fixes service lifecycle management issues when state file is deleted which service is running. Closes #872
  cmd/service.go
  db/local_db/locations.go
  db/local_db/query.go
  db/local_db/start_database.go
  db/local_db/status.go
  db/local_db/stop_database.go
Labels: bug

#899 Fix issue where `service stop` shuts down service even if non-steampipe clients are connected. Closes #887
  db/local_db/stop_database.go
Labels: bug

#906 Add acceptance test for `force stop` works after state file deletion. closes #905
  tests/acceptance/test_files/099.force-stop.bats
Labels: test

#826 Small updates to `steampipe service *` commands. Closes #812
  .github/workflows/test.yml
  cmd/service.go
  db/db_local/running_info.go
  tests/acceptance/test_files/004.query.bats
  tests/acceptance/test_files/012.cache.bats
Labels: ui

#900 Adds support for outputting `stdout` and `stderr` from `service start` to `TRACE log`. Closes #810
  db/db_local/start_database.go
Labels: enhancement

#923 Fix issue where `install.sh` fails for IPv6 enabled system. Closes #861
  install.sh
Labels: bug

#914 Add acceptance test for testing time required to query a chaos table. closes #913
  tests/acceptance/run-local.sh
  tests/acceptance/run.sh
  tests/acceptance/test_files/015.time-to-query.bats
Labels: test

#935 Allow for setting service password from `ENV` or `cmd` flag. Closes #725
  cmd/service.go
  cmdconfig/viper.go
  constants/args.go
  constants/env.go
  db/db_local/install.go
  db/db_local/locations.go
  db/db_local/password.go
  db/db_local/start_database.go
  db/db_local/stop_database.go
  tests/acceptance/test_files/003.service-password.bats
  tests/acceptance/test_files/004.plugin.bats
  tests/acceptance/test_files/006.query.bats
  tests/acceptance/test_files/007.search-path.bats
Labels: enhancement

#942 Fix issue where service tx hangs and introspection table disappear on timout. Closes #939
  cmd/check.go
  cmd/query.go
  db/db_client/db_client.go
  db/db_client/db_client_execute.go
  db/db_common/client.go
  db/db_common/wait_connection.go
  db/db_local/create_client.go
  db/db_local/local_db_client.go
  workspace/service_state.go
Labels: bug

#952 Fix for issue where `service start` logs are not coming up on `TRACE`. Closes #950
  db/db_local/start_database.go
Labels: bug

#958 Add support for rotating service password in Docker images. Closes #957
  Dockerfile
Labels: enhancement

#863 Allow plugin uninstall even if there are active connections. Closes #852
  cmd/plugin.go
  db/db_local/local_db_client.go
  plugin/actions.go
  steampipeconfig/connection_plugin.go
  steampipeconfig/connection_updates.go
  steampipeconfig/load_config.go
  steampipeconfig/modconfig/connection.go
  steampipeconfig/parse/connection.go
  steampipeconfig/parse/options.go
  steampipeconfig/shared.go
Labels: enhancement

#966 Acceptance tests for introspection table updates. Closes #962
  tests/acceptance/run.sh
  tests/acceptance/test_data/introspection_table_mod/control.sp
  tests/acceptance/test_data/introspection_table_mod/mod.sp
  tests/acceptance/test_data/introspection_table_mod/query.sp
  tests/acceptance/test_files/016.introspection-tables.bats
Labels: test
