Repository turbot/steampipe, pull requests merged in 2021-07, with the labels that each got.

#586 Fix issue where using `--timing` with `check` was not showing duration. Fixes #571
  cmd/check.go
  control/execute/control_run.go
  control/execute/result_group.go
Labels: bug

#566 Fix: Linux Installer. Closes #538
  install.sh
Labels: bug

#588 Fix issue where `dimension` values were not rendered in generated CSV for `check`. Closes #587
  control/controldisplay/csv.go
  tests/acceptance/test_data/templates/expected_check_csv.csv
  tests/acceptance/test_data/templates/expected_check_csv_noheader.csv
  tests/acceptance/test_data/templates/expected_check_separator_csv.csv
Labels: bug

#568 Updates to steampipe service. Closes #523.
  .github/workflows/test.yml
  cmd/plugin.go
  cmd/query.go
  cmd/root.go
  cmd/service.go
  cmdconfig/builder.go
  constants/args.go
  db/client.go
  db/client_connections.go
  db/functions.go
  db/install.go
  db/interactive_client.go
  db/locations.go
  db/metadata_tables.go
  db/pid_exists.go
  db/query.go
  db/running_info.go
  db/schema.go
  db/start_database.go
  db/start_service.go
  db/status.go
  db/stop_database.go
  main.go
  query/execute/execute.go
  query/execute/resolve.go
  steampipeconfig/connection_state.go
  steampipeconfig/connection_updates.go
  steampipeconfig/load_config.go
  task/runner.go
  tests/acceptance/test_files/000.basics.bats
  tests/acceptance/test_files/004.query.bats
  tests/acceptance/test_files/005.chaos.bats
  tests/acceptance/test_files/007.matrix.bats
  tests/acceptance/test_files/008.check.bats
  utils/hash.go
  workspace/workspace.go
Labels: house-keeping

#596 Fix for issue where `query` freezes if there's no data on `stdin`. Closes #570
  cmd/query.go
Labels: bug

#601 `plugin install` creates `temp` files in `$STEAMPIPE_INSTALL_DIR/plugins` during plugin install. Closes #600. Closes #527
  ociinstaller/tempdir.go
Labels: enhancement

#609 `initdb` even if databasse is installed but `data directory` is empty. Closes #575
  cmd/service.go
  db/install.go
  db/start_database.go
  db/start_service.go
  db/stop_database.go
Labels: enhancement

#616 Fixes issue where `STEAMPIPE_INSTALL_DIR` is not being used. Closes #613
  cmd/root.go
  cmdconfig/viper.go
  constants/env.go
Labels: bug

#618 Takes alternate approach to service status by using Pid listing instead of `ps` spawn
  db/pid_exists.go
Labels: bug

#624 Fixes issue where `stop --force` on an `implicit` service prevents another `implicit` service from starting. Closes #622
  db/query.go
  db/start_database.go
  db/start_service.go
  db/stop_database.go
Labels: bug

#635 Fixes issue where `initdb` fails because of missing permissions and users. Closes #634
  db/client.go
  db/install.go
  db/start_database.go
  db/stop_database.go
  query/execute/execute.go
Labels: bug

#640 Fixes issue where `data-dir` was being removed instead of it's contents during `init`. Closes #639
  db/install.go
  utils/remove_dir_contents.go
Labels: bug

#646 Fixes issue where spinner message is not shown for `FDW` update. Closes #643
  db/install.go
  display/spinner.go
Labels: bug

#654 Fixes issue where `service stop` does not work in `linux` systems. Closes #653
  db/pid_exists.go
  db/stop_database.go
Labels: bug

#661 Fixes issue where service is started even when `data-dir` is not writable . Closes #659
  db/start_database.go
  db/start_service.go
  utils/fs_permissions.go
Labels: bug

#681 Fixes `nil pointer exception` in `steampipe plugin`. Closes #678
  cmd/plugin.go
  cmdconfig/builder.go
Labels: bug

#663 Add `Dockerfile` for steampipe and automated image deploy. Closes #662. Closes #677
  .github/workflows/publish_docker.yml
  .github/workflows/release.yml
  Dockerfile
  docker-entrypoint.sh
Labels: devops

#699 Add tests for `parent` commands. Closes #685
  tests/acceptance/test_data/templates/expected_plugin_help_output.txt
  tests/acceptance/test_data/templates/expected_service_help_output.txt
  tests/acceptance/test_files/000.basics.bats
Labels: test
