Repository turbot/steampipe, pull requests merged in 2022-11, with the labels that each got.

#2642 Fix and re-enable docker tests in release workflow
  .github/workflows/release_cli_and_assets.yml
  .github/workflows/test.yml
  tests/acceptance/run.sh
  tests/acceptance/test_data/source_files/aggregator.spc
  tests/acceptance/test_files/service_and_plugin.bats
  tests/dockertesting/debian/run-tests.sh
  tests/dockertesting/oraclelinux/run-tests.sh
Labels: github_actions

#2475 Fix unintuitive errors from steampipe plugin commands when a plugin (version) is missing
  cmd/plugin.go
  pkg/db/db_local/local_db_client_connections.go
  pkg/display/display.go
  pkg/steampipeconfig/connection_data_map.go
  pkg/steampipeconfig/connection_schemas.go
  pkg/steampipeconfig/connection_updates.go
  pkg/steampipeconfig/refresh_connections_result.go
  pkg/utils/plugin.go
Labels: bug

#2694 Consolidates setting of CLI flag shorthand
  cmd/check.go
  cmd/completion.go
  cmd/dashboard.go
  cmd/login.go
  cmd/mod.go
  cmd/plugin.go
  cmd/query.go
  cmd/service.go
  cmd/variable.go
  pkg/cmdconfig/builder.go
  pkg/cmdconfig/cmd_flags.go
Labels: house-keeping

#2718 Reverts update of google-github-actions/setup-gcloud from 0.6.2 to 1.0.0
  .github/workflows/buildDBImage.yml
  .github/workflows/release_cli_and_assets.yml
Labels: devops

#2744 Fixes issue where upgrading to the new 'google-github-actions/setup-gcloud' was causing issues with authentication
  .github/workflows/buildDBImage.yml
  .github/workflows/release_cli_and_assets.yml
Labels: devops

#2764 Fixes issue where a '--where' or '--tag' flag were not creating the introspection tables.
  cmd/check.go
  pkg/control/init_data.go
Labels: bug

#2738 Fixes issue where control execution errors were not shown in CSV rendering.
  pkg/control/controldisplay/templates/csv/output.tmpl
  pkg/control/controldisplay/templates/csv/version.json
  pkg/control/controlexecute/control_run.go
Labels: bug

#2725 Add acceptance tests for connecting to Steampipe cloud. Closes #2370
  .github/workflows/test.yml
  tests/acceptance/run-local.sh
  tests/acceptance/run.sh
  tests/acceptance/test_files/cloud.bats
  tests/dockertesting/debian/run-tests.sh
  tests/dockertesting/oraclelinux/run-tests.sh
Labels: test

#2782 Upgrades 'pgx' to v5
  go.mod
  go.sum
  main.go
  pkg/control/controlexecute/result_row.go
  pkg/db/db_client/db_client.go
  pkg/db/db_client/db_client_connect.go
  pkg/db/db_client/db_client_execute.go
  pkg/db/db_client/db_client_session.go
  pkg/db/db_client/pgx_types.go
  pkg/db/db_common/db_session.go
  pkg/db/db_common/introspection_tables.go
  pkg/db/db_common/schema.go
  pkg/db/db_common/tls_config.go
  pkg/db/db_common/wait_connection.go
  pkg/db/db_local/create_client.go
  pkg/db/db_local/execute.go
  pkg/db/db_local/install.go
  pkg/db/db_local/local_db_client_connections.go
  pkg/db/db_local/start_services.go
  pkg/display/column.go
  pkg/initialisation/init_data.go
  pkg/query/queryresult/column_def.go
  pkg/type_conversion/postgres_conversion.go
  pkg/utils/collection.go
  pkg/workspace/session_data.go
Labels: house-keeping

#2790 Update postgres config to reverts max_locks_per_transaction to pre 0.17.0 value of 2048
  pkg/constants/postgresql_conf.go
Labels: house-keeping

#2795 Fixes issue where unit tests were not running on new Pull Requests
  .github/workflows/release_cli_and_assets.yml
  .github/workflows/test.yml
  pkg/steampipeconfig/load_config_test.go
  pkg/steampipeconfig/load_mod_test.go
  pkg/steampipeconfig/modconfig/parsed_property_path_test.go
  pkg/steampipeconfig/modconfig/query_args.go
  pkg/steampipeconfig/modconfig/query_args_helpers.go
  pkg/steampipeconfig/modconfig/query_args_test.go
  pkg/steampipeconfig/parse/prepared_statement.go
  pkg/steampipeconfig/parse/prepared_statement_test.go
  pkg/steampipeconfig/testdata/connection_config/options_duplicate_block/config/default.spc
  pkg/steampipeconfig/testdata/connection_config/options_duplicate_block/config/default2.spc
  pkg/steampipeconfig/testdata/connection_config/options_only/config/default.spc
  pkg/steampipeconfig/testdata/connection_config/single_connection_with_default_and_connection_options/config/default.spc
  pkg/steampipeconfig/testdata/connection_config/single_connection_with_default_options/config/default.spc
  pkg/workspace/workspace_queries.go
Labels: house-keeping

#2799 Fixes issue where 'oras' is failing to parse date provided in annotations file
  .github/workflows/buildDBImage.yml
  .github/workflows/release_cli_and_assets.yml
Labels: house-keeping

#2755 Adds a '--max-parallel' (hidden) flag to 'steampipe dashboard'.
  cmd/check.go
  cmd/dashboard.go
  pkg/constants/db.go
Labels: enhancement

#2686 Modifies unit tests for the new FormatterResolver
  pkg/control/controldisplay/formatter_test.go
  pkg/export/manager.go
  pkg/export/manager_test.go
  pkg/export/snapshot_exporter.go
Labels: test

#2775 Updates the update checker to run asynchronously.
  cmd/plugin.go
  cmd/root.go
  pkg/db/db_local/logs.go
  pkg/filepaths/steampipe.go
  pkg/plugin/version_checker.go
  pkg/statefile/state.go
  pkg/task/display.go
  pkg/task/pluginversioncheck.go
  pkg/task/runner.go
  pkg/task/version_checker.go
  pkg/utils/useragent.go
  tests/acceptance/test_files/service_and_plugin.bats
Labels: enhancement

#2759 Update release workflow to support brew formula versioning. Closes #2758
  .github/workflows/release_cli_and_assets.yml
  .goreleaser.yml
Labels: devops

#2720 Fixes issue where interactive prompt was not showing timing data for 'json', 'csv' and 'line' outputs.
  cmd/query.go
  pkg/db/db_client/db_client.go
  pkg/display/display.go
  pkg/query/queryexecute/execute.go
Labels: bug

#2808 Fixes issue where value from '--separator' was not being used in CSV rendering.
  cmd/check.go
  pkg/control/controldisplay/csv.go
  pkg/control/controldisplay/formatter_template.go
  pkg/control/controldisplay/template_functions.go
  pkg/control/controldisplay/template_functions_test.go
  pkg/control/controldisplay/template_render_context.go
  pkg/control/controldisplay/templates/csv/output.tmpl
  pkg/control/controldisplay/templates/csv/version.json
  tests/acceptance/test_data/templates/expected_check_csv_pipe_separator.csv
  tests/acceptance/test_files/check.bats
Labels: bug
