Repository turbot/steampipe, pull requests merged in 2022-01, with the labels that each got.

#1271 Fix issue where database name is not printed in output of 'service start'
  db/db_local/start_services.go
  tests/acceptance/test_files/002.service.bats
Labels: bug

#1276 Removes transaction creation around query execution. Closes #1241
  db/db_client/db_client_execute.go
  db/db_client/db_client_transaction.go
Labels: house-keeping

#1261 Fix issue where benchmark execution duration is incorrect in check. Closes #1249
  cmd/check.go
  control/controlexecute/control_run.go
  control/controlexecute/execution_tree.go
  control/controlexecute/result_group.go
  db/db_client/db_client_session.go
  db/db_common/db_session.go
  db/db_common/introspection_tables.go
  plugin_manager/plugin_manager.go
  utils/lifecycle_timer.go
Labels: bug

#1280 Fix issue where service is not shutdown if interrupted while interactive prompt is initialising. Closes #1004
  cmd/query.go
  db/db_local/create_client.go
  db/db_local/start_services.go
  interactive/interactive_client.go
  interactive/interactive_client_init.go
  interactive/run.go
  query/init_data.go
  query/query_init_data.go
  query/queryexecute/execute.go
Labels: bug

#1302 Fixes issue where check table output is not getting displayed at all. Closes #1300
  control/controlexecute/result_group.go
Labels: bug

#1308 Add support for a generic template formatter for check output. Closes #1289
  cmd/check.go
  constants/output_format.go
  control/controldisplay/export_template.go
  control/controldisplay/formatter.go
  control/controldisplay/formatter_csv.go
  control/controldisplay/formatter_fs.go
  control/controldisplay/formatter_html.go
  control/controldisplay/formatter_json.go
  control/controldisplay/formatter_markdown.go
  control/controldisplay/formatter_template.go
  control/controldisplay/formatter_template_test.go
  control/controldisplay/formatter_test.go
  control/controldisplay/formatter_text.go
  control/controldisplay/templates/asff.json/001.asff.tmpl.json
  control/controldisplay/templates/html.html/001.index.tmpl.html
  control/controldisplay/templates/html.html/favicon.b64
  control/controldisplay/templates/html.html/logo.b64
  control/controldisplay/templates/html.html/normalize.tmpl.css
  control/controldisplay/templates/html.html/style.tmpl.css
  control/controldisplay/templates/markdown.md/001.index.tmpl.md
  control/controldisplay/templates/nunit3.xml/001.nunit3.tmpl.xml
  control/controlexecute/dimension_color_map.go
  control/controlexecute/execution_tree.go
  control/controlexecute/status_summary.go
  control/export_data.go
  filepaths/steampipe.go
  tests/acceptance/test_data/templates/expected_check_html.html
  tests/acceptance/test_data/templates/expected_check_markdown.md
  tests/acceptance/test_data/templates/expected_check_nunit3.xml
  tests/acceptance/test_files/008.check.bats
  tests/acceptance/test_files/009.check-search-path.bats
  tests/acceptance/test_files/010.connection.bats
  tests/acceptance/test_files/012.cache.bats
  tests/acceptance/test_files/013.query-params.bats
Labels: enhancement

#1319 Fixes issue in plugin manager where plugin shutdown and process killing messages were logging in at WARN level. Closes #1309
  pluginmanager/plugin_manager.go
Labels: bug

#1325 Fixes issue where plugins were logging using a different time format from FDW and Database. Closes #927
  .github/workflows/test.yml
  cmd/plugin_manager.go
  cmd/root.go
  constants/postgresql_conf.go
  go.mod
  go.sum
Labels: bug

#1333 v0.12.0
  CHANGELOG.md
  version/version.go
Labels: release

#1351 Enforce timezone in local test bed. Closes #1350
  tests/acceptance/run-local.sh
Labels: test

#1339 CSV template for check export. Closes #1315
  cmd/check.go
  control/controldisplay/formatter.go
  control/controldisplay/formatter_csv.go
  control/controldisplay/formatter_test.go
  control/controldisplay/template_functions.go
  control/controldisplay/template_functions_test.go
  control/controldisplay/templates/csv/output.tmpl
  go.mod
  go.sum
  no-header.csv
  tests/acceptance/test_files/008.check.bats
  yes-header.csv
Labels: controls

#1361 Fix issues reported by the 'unused', 'staticcheck', 'gosimple' linters. closes #1360
  .golangci.yml
  interactive/interactive_client.go
  pluginmanager/plugin_manager.go
  query/metaquery/completers.go
  steampipeconfig/connection_test.go
  steampipeconfig/parse/decode.go
Labels: house-keeping
