Repository turbot/steampipe, pull requests merged in 2022-05, with the labels that each got.

#2006 Packaging of underlying postgresql. Closes #2005
  .github/workflows/buildDBImage.yml
  constants/db.go
  db/db_local/backup.go
Labels: house-keeping

#2013 Trims the least recently created backups. Closes #2012
  db/db_local/backup.go
  db/db_local/backup_test.go
  task/runner.go
  utils/collection.go
Labels: house-keeping

#2043 Fix backward compatibility issues in config file migration. Closes #2042
  ociinstaller/versionfile/db_version_file.go
  ociinstaller/versionfile/installed_version.go
  ociinstaller/versionfile/plugin_version_file.go
  statefile/state.go
Labels: bug

#2054 Add acceptance test to verify public schema migration. Closes #2053
  tests/acceptance/test_files/024.public-schema-migration.bats
Labels: test

#1969 Add control severity in the check run CSV output. Closes #1966
  control/controldisplay/templates/csv/output.tmpl
  tests/acceptance/test_data/templates/expected_check_csv.csv
  tests/acceptance/test_data/templates/expected_check_csv_noheader.csv
  tests/acceptance/test_data/templates/expected_check_csv_sorted_tags.csv
Labels: bug

#2124 Fix intermittent unrecognized remote plugin message after update/make plugins
  ociinstaller/fdw.go
  ociinstaller/plugin.go
Labels: bug
