Repository turbot/steampipe, pull requests merged in 2022-03, with the labels that each got.

#1484 Installs dashboard assets as part of docker image build. Closes #1482
  Dockerfile
Labels: devops

#1502 Fix issue where schema extraction is broken for remote services. Closes #1497
  db/db_client/db_client.go
  db/db_common/client.go
  db/db_local/local_db_client.go
  interactive/interactive_client.go
Labels: bug

#1586 Fix issue where `plugin-manager` becomes unstable if plugins crash. Closes #1453
  pluginmanager/plugin_manager.go
Labels: bug

#1596 Fixes issue where dashboard starts even if there's a port clash. Closes #1579
  cmd/dashboard.go
  constants/exit_codes.go
  dashboard/dashboardserver/service.go
  db/db_local/start_services.go
  utils/net.go
Labels: bug

#1581 Expand dashboard parsing unit tests. Closes #1562
  steampipeconfig/load_mod_test.go
  steampipeconfig/testdata/mods/anonymous_input/dashboard.sp
  steampipeconfig/testdata/mods/anonymous_input/mod.sp
  steampipeconfig/testdata/mods/anonymous_top_level_resource/dashboard.sp
  steampipeconfig/testdata/mods/anonymous_top_level_resource/mod.sp
  steampipeconfig/testdata/mods/dashboard_with_child_dashboard/dashboard.sp
  steampipeconfig/testdata/mods/dashboard_with_child_dashboard/mod.sp
  steampipeconfig/testdata/mods/dashboard_with_named_child_res/dashboard.sp
  steampipeconfig/testdata/mods/dashboard_with_named_child_res/mod.sp
  steampipeconfig/testdata/mods/duplicate_dashboard/dashboard.sp
  steampipeconfig/testdata/mods/duplicate_dashboard/mod.sp
  steampipeconfig/testdata/mods/inputs_with_cyclic_dependency/dashboard.sp
  steampipeconfig/testdata/mods/inputs_with_cyclic_dependency/mod.sp
  steampipeconfig/testdata/mods/wrong_title_referencing/dashboard.sp
  steampipeconfig/testdata/mods/wrong_title_referencing/mod.sp
  workspace/test_data/dependent_mod/.mod.cache.json
  workspace/test_data/dependent_mod/README.md
  workspace/test_data/dependent_mod/dashboard.sp
  workspace/test_data/dependent_mod/mod.sp
  workspace/test_data/dependent_mod_2/.mod.cache.json
  workspace/test_data/dependent_mod_2/README.md
  workspace/test_data/dependent_mod_2/dashboard.sp
  workspace/test_data/dependent_mod_2/mod.sp
  workspace/workspace_test.go
Labels: test

#1622 Expand plugin query tests. Closes #1621
  tests/acceptance/test_files/002.service.bats
Labels: test

#1655 Re-design and update cache acceptance tests. Closes #1570
  tests/acceptance/test_data/config_parsing_test_mod/query.sp
  tests/acceptance/test_data/functionality_test_mod/query/check_cache.sql
  tests/acceptance/test_files/010.connection.bats
  tests/acceptance/test_files/012.cache.bats
Labels: test

#1658 Enable dependabot to scan and update ui/dashboard deps as well. Closes #1642
  .github/dependabot.yml
Labels: house-keeping

#1677 Adds 'search-path' and 'variable' flags to 'dashboard' cmd. Closes #1674
  .github/dependabot.yml
  cmd/dashboard.go
Labels: bug

#1632 Fix unit tests. Closes #1611
  .github/workflows/test.yml
  control/controldisplay/formatter_template_test.go
  control/controldisplay/group_counter_test.go
  control/controldisplay/group_title_test.go
  control/controldisplay/result_reason_test.go
  control/controldisplay/result_status_test.go
  control/controldisplay/spacer_test.go
  control/controldisplay/table_test.go
  pluginmanager/plugin_path.go
  steampipeconfig/connection_test.go
  steampipeconfig/load_config_test.go
  steampipeconfig/load_mod.go
  steampipeconfig/load_mod_test.go
  steampipeconfig/modconfig/query_args.go
  steampipeconfig/parse/prepared_statement_test.go
  steampipeconfig/shared_test.go
  steampipeconfig/testdata/workspaces/empty/.gitstub
  workspace/test_data/dependent_mod/.steampipe/mods/github.com/pskrbasu/steampipe-mod-m1@4.0/.gitignore
  workspace/test_data/dependent_mod/.steampipe/mods/github.com/pskrbasu/steampipe-mod-m1@4.0/dashboard.sp
  workspace/test_data/dependent_mod/.steampipe/mods/github.com/pskrbasu/steampipe-mod-m1@4.0/mod.sp
  workspace/test_data/dependent_mod/.steampipe/mods/github.com/pskrbasu/steampipe-mod-m1@4.0/query.sp
  workspace/test_data/dependent_mod_2/.steampipe/mods/github.com/pskrbasu/steampipe-mod-m1@4.0/.gitignore
  workspace/test_data/dependent_mod_2/.steampipe/mods/github.com/pskrbasu/steampipe-mod-m1@4.0/dashboard.sp
  workspace/test_data/dependent_mod_2/.steampipe/mods/github.com/pskrbasu/steampipe-mod-m1@4.0/mod.sp
  workspace/test_data/dependent_mod_2/.steampipe/mods/github.com/pskrbasu/steampipe-mod-m1@4.0/query.sp
Labels: test

#1678 Fixes issue where installing a 'non-latest' plugin will not install config even if it's not there. Closes #1660
  ociinstaller/assets.go
  ociinstaller/db.go
  ociinstaller/fdw.go
  ociinstaller/plugin.go
  ociinstaller/plugin_test.go
  ociinstaller/steampipeimage.go
  ociinstaller/zip.go
Labels: bug

#1697 v0.13.1
  CHANGELOG.md
  version/version.go
Labels: release

#1712 Fix issue where dashboard isn't shutting down even with unmet plugin dependency. Closes #1711
  cmd/dashboard.go
Labels: bug

#1745 Fixes issue where tags are not sorted in output of 'check' command. Closes #1715
  control/controlexecute/execution_tree.go
  control/controlexecute/result_group.go
  tests/acceptance/test_data/control_rendering_test_mod/query/gen_query_with_dimensions.sp
  tests/acceptance/test_data/control_rendering_test_mod/query/gen_query_with_dimensions.sql
  tests/acceptance/test_data/control_rendering_test_mod/sp_check_test/control_check_rendering.sp
  tests/acceptance/test_data/templates/expected_check_csv_sorted_tags.csv
  tests/acceptance/test_files/008.check.bats
Labels: bug
