Repository turbot/steampipe, pull requests merged in 2022-04, with the labels that each got.

#1757 Fixes issue where implicit service was always using a default port. Closes #1753
  cmdconfig/viper.go
  db/db_local/local_db_client.go
Labels: bug

#1807 Add acceptance test for connection name escaping. Closes #1772
  tests/acceptance/test_data/source_files/chaos_conn_name_escaping.spc
  tests/acceptance/test_files/010.connection.bats
Labels: test

#1790 Update CLI version of Go to 1.18. Closes #1783
  .github/workflows/test.yml
  go.mod
  go.sum
Labels: house-keeping

#1793 Fix issue where plugin install always install amd64 for plugins.
  ociinstaller/steampipeimage.go
Labels: bug

#1823 Migrate all json config files to use snake case property names. Closes #1730
  cmd/root.go
  dashboard/dashboardserver/service.go
  db/db_local/running_info.go
  filepaths/steampipe.go
  migrate/migrate.go
  ociinstaller/versionfile/db_version_file.go
  ociinstaller/versionfile/legacy_version_file.go
  ociinstaller/versionfile/plugin_version_file.go
  pluginmanager/grpc/proto/simple_addr.go
  pluginmanager/state.go
  statefile/load.go
  statefile/save.go
  steampipeconfig/connection_data.go
  steampipeconfig/connection_data_map.go
  steampipeconfig/modconfig/connection.go
  steampipeconfig/versionmap/resolved_version_constraint.go
  steampipeconfig/versionmap/workspace_lock.go
  tests/acceptance/test_files/002.service.bats
  tests/acceptance/test_files/003.service-password.bats
  workspace/workspace.go
Labels: house-keeping

#1809 Separate release creation and publish workflows and remove legacy workflows. Closes #1441
  .github/workflows/buildassetsimage.yml
  .github/workflows/release_cli_and_assets.yml
Labels: house-keeping

#1858 Add support for plugins to switch over to arm64 build for darwin even in the same version. Closes #1796
  cmd/plugin.go
  constants/platform.go
  ociinstaller/mediatypes.go
  ociinstaller/plugin.go
  ociinstaller/steampipeimage.go
  ociinstaller/versionfile/db_version_file.go
  ociinstaller/versionfile/installed_version.go
  plugin/update.go
  plugin/version_check_payload.go
  plugin/version_checker.go
Labels: enhancement

#1888 Update install script to support installation of arm64 for Darwin and aarch64 for Linux. Closes #1887
  install.sh
Labels: installation

#1808 Various updates to plugin operations UX including async update and install.
  cmd/plugin.go
  display/plugin_install.go
  display/plugin_remove.go
  go.mod
  go.sum
  ociinstaller/plugin.go
  plugin/actions.go
  utils/map.go
Labels: plugin installation, ui, cli output

#1898 Fixes issue where plugin install crashes for non-existent plugins. Closes #1896
  cmd/plugin.go
  constants/plugin.go
  display/plugin_install.go
Labels: bug

#1881 Fix the in-place switch over to ARM for plugins . Closes #1880
  plugin/update.go
  task/pluginversioncheck.go
Labels: update unreleased feature

#1892 Detect the underlying arch to install the correct FDW package. Closes #1889
  ociinstaller/mediatypes.go
  ociinstaller/steampipeimage.go
  utils/arch.go
Labels: installation

#1927 Maintain backward and forward compatibility during state and version file migrations. Closes #1913
  cmd/root.go
  dashboard/dashboardserver/service.go
  db/db_local/local_db_client_connections.go
  db/db_local/running_info.go
  migrate/migrate.go
  ociinstaller/versionfile/db_version_file.go
  ociinstaller/versionfile/installed_version.go
  ociinstaller/versionfile/plugin_version_file.go
  pluginmanager/state.go
  statefile/state.go
  steampipeconfig/connection_data.go
  steampipeconfig/connection_data_map.go
  steampipeconfig/connection_state.go
  steampipeconfig/connection_test.go
  steampipeconfig/load_config_test.go
  steampipeconfig/modconfig/connection.go
  steampipeconfig/options/connection.go
  steampipeconfig/testdata/mods/report_test/.mod.cache.json
  steampipeconfig/versionmap/workspace_lock.go
  workspace/workspace.go
Labels: update unreleased feature

#1963 Fixes issue where a warning was not being shown when matview REFRESH wasn't successful. Closes #1962
  db/db_local/backup.go
Labels: bug

#1979 Fixes issue where 'pg_dump' and 'pg_restore' depends on system libraries instead of packaged ones. Closes #1972
  db/db_local/backup.go
  db/db_local/locations.go
Labels: bug
