Repository turbot/steampipe, pull requests merged in 2023-04, with the labels that each got.

#3289 Fixes issue where execution continues even if there's an unexpected error in parsing config
  cmd/root.go
Labels: bug

#3290 Fixes issue where installing transitive mod dependencies leaves the lock file in a bad state
  pkg/modinstaller/mod_installer.go
Labels: bug

#3295 Fixes issue where mod install/update continues installation even with unsatisfied requirements
  pkg/filepaths/workspace.go
  pkg/modinstaller/mod_installer.go
  pkg/modinstaller/resolved_mod_ref.go
  pkg/steampipeconfig/modconfig/mod_name.go
  pkg/steampipeconfig/parse/mod_parse_context.go
  pkg/steampipeconfig/versionmap/resolved_version_constraint.go
Labels: bug

#3321 Show plugin name with stream in the progress bar during plugin update
  cmd/plugin.go
  pkg/plugin/version_checker.go
Labels: enhancement

#3318 Use --clean flag instead of deprecated --rm-dist. Closes #3317
  .github/workflows/release_cli_and_assets.yml
  .github/workflows/test.yml
Labels: github_actions

#3320 Update Publish Release workflow to push to both dockerhub and ghcr. Closes #3319
  .github/workflows/publish_docker.yml
Labels: github_actions

#3326 Fixes issue where having non graphic code points in output would mess up table output in interactive
  pkg/display/display.go
Labels: bug

#3331 Show stream name only for non-latest streams in plugin update output. Closes #3330
  pkg/plugin/version_checker.go
Labels: cli output

#3334 Fixes issue where running mods with unmet dependencies does not raise warnings
  pkg/initialisation/init_data.go
  pkg/plugin/installed.go
  pkg/steampipeconfig/modconfig/mod.go
  pkg/steampipeconfig/modconfig/mod_resources.go
  pkg/steampipeconfig/modconfig/require.go
  pkg/workspace/workspace_require.go
  tests/acceptance/test_files/mod.bats
Labels: bug

#3282 Do not show deprecation warnings every time while running any steampipe command. Closes #3281
  cmd/root.go
  pkg/steampipeconfig/steampipeconfig.go
  pkg/task/config.go
  pkg/task/runner.go
Labels: update unreleased feature

#3328 Fixes issue where a mod would install even if plugin dependencies are not met
  cmd/mod.go
  pkg/initialisation/init_data.go
  pkg/modinstaller/install.go
  pkg/modinstaller/install_opts.go
  pkg/modinstaller/mod_installer.go
  pkg/steampipeconfig/modconfig/require.go
  tests/acceptance/test_files/mod.bats
  tests/acceptance/test_files/mod_install.bats
Labels: bug

#3363 Fixes issue where mod installation would fail silently for unmet dependencies in top mod in force mode. Closes #3358
  pkg/initialisation/init_data.go
  pkg/modinstaller/mod_installer.go
  pkg/steampipeconfig/modconfig/mod.go
  pkg/steampipeconfig/modconfig/require.go
  pkg/workspace/workspace_require.go
  tests/acceptance/test_files/mod_install.bats
Labels: bug, update unreleased feature
