Repository turbot/steampipe, pull requests merged in 2023-02, with the labels that each got.

#3056 Fix issue where snapshot creation was failing for command line queries in batch mode. Closes #2943
  cmd/query.go
Labels: bug

#3069 Add a helpful error message when snapshot sharing fails because of a corrupted/invalid token. Closes #2944
  pkg/cloud/workspace.go
  pkg/error_helpers/errors.go
Labels: enhancement

#3046 Fix query batch mode returning zero exit code when rows return errors. Closes #3044
  cmd/query.go
  pkg/display/display.go
  pkg/query/queryexecute/execute.go
Labels: bug

#3062 Fixes issue where config from 'default.spc' was taking precedence over ENV var settings
  cmd/root.go
  pkg/cmdconfig/viper.go
  tests/acceptance/test_data/source_files/config_tests/default.spc
  tests/acceptance/test_data/source_files/config_tests/workspace_tests.json
  tests/acceptance/test_files/workspace.bats
Labels: bug

#3070 Add logs in test workflow to debug intermittent failures/stalls #3037
  .github/workflows/test.yml
  tests/acceptance/test_files/check.bats
Labels: test

#3073 Fixes issue where update notifications shows empty box on no notification
  pkg/task/available_versions.go
  pkg/task/display.go
Labels: bug, update unreleased feature

#3092 Fixes issue where autocomplete does not quote table names that need to be quoted. Closes #3065
  pkg/interactive/autocomplete.go
  pkg/utils/string.go
  pkg/utils/string_slice.go
Labels: bug

#3096 Fixes issue where '.inspect' was not working for table names with a '.'
  pkg/db/db_common/schema.go
  pkg/query/metaquery/handlers.go
  pkg/schema/schema.go
Labels: bug

#3107 Fix issue where check csv output was appending an extra line at the end. Closes #3106
  pkg/control/controldisplay/templates/csv/output.tmpl
  pkg/control/controldisplay/templates/csv/version.json
Labels: bug

#3055 Tweaks to service startup
  pkg/cmdconfig/diagnostics.go
  pkg/cmdconfig/viper.go
  pkg/constants/args.go
  pkg/constants/default_options.go
  pkg/constants/duration.go
  pkg/constants/env.go
  pkg/db/db_client/db_client_connect.go
  pkg/db/db_common/wait_connection.go
  pkg/db/db_local/create_client.go
  pkg/steampipeconfig/options/database.go
Labels: enhancement

#3113 Fixes issue where snapshot mode in query leads to duplicate rows in console/file output
  .github/workflows/release_cli_and_assets.yml
  .github/workflows/test.yml
  cmd/query.go
  tests/acceptance/test_data/functionality_test_mod/query/static_query_2.sql
  tests/acceptance/test_data/templates/expected_static_query_csv_snapshot_mode.csv
  tests/acceptance/test_data/templates/expected_static_query_json_snapshot_mode.json
  tests/acceptance/test_data/templates/expected_static_query_table_snapshot_mode.txt
  tests/acceptance/test_files/snapshot.bats
Labels: bug

#3118 Update the snapshot acceptance tests to delete the snapshot created after each test run to avoid exceeding quota. Closes #3117
  tests/acceptance/test_files/snapshot.bats
  tests/acceptance/test_files/url_parse.sh
Labels: test

#3120 Adds a mechanism for status updates during initialisation
  pkg/db/db_common/wait_connection.go
  pkg/db/db_local/create_client.go
  pkg/initialisation/init_data.go
  pkg/initialisation/init_hook.go
  pkg/interactive/interactive_client.go
Labels: enhancement

#3121 Fixes issue where variables list command was not including description in JSON output. Closes #3114
  pkg/display/variables.go
Labels: bug, cli output

#3140 Fixes issue where spinner is left behind in 'plugin list'
  cmd/plugin.go
Labels: bug

#3144 Adds better error messages for db connection timeouts
  pkg/db/db_local/create_client.go
  sperr/error.go
  sperr/factory.go
Labels: ui

#3151 Add acceptance tests for dynamic aggregators
  .github/workflows/release_cli_and_assets.yml
  .github/workflows/test.yml
  tests/acceptance/run-local.sh
  tests/acceptance/test_data/source_files/dynamic_aggregator_tests/dynamic_aggregator_col_mismatch.spc
  tests/acceptance/test_data/source_files/dynamic_aggregator_tests/dynamic_aggregator_col_type_mismatch.spc
  tests/acceptance/test_data/source_files/dynamic_aggregator_tests/dynamic_aggregator_col_type_mismatch_2.spc
  tests/acceptance/test_data/source_files/dynamic_aggregator_tests/dynamic_aggregator_col_type_mismatch_3.spc
  tests/acceptance/test_data/source_files/dynamic_aggregator_tests/dynamic_aggregator_col_type_mismatch_4.spc
  tests/acceptance/test_data/source_files/dynamic_aggregator_tests/dynamic_aggregator_same_table_cols.spc
  tests/acceptance/test_data/source_files/dynamic_aggregator_tests/dynamic_aggregator_table_mismatch.spc
  tests/acceptance/test_data/templates/dynamic_aggregators_col_mismatch.json
  tests/acceptance/test_data/templates/dynamic_aggregators_col_type_mismatch.json
  tests/acceptance/test_data/templates/dynamic_aggregators_col_type_mismatch_2.json
  tests/acceptance/test_data/templates/dynamic_aggregators_col_type_mismatch_3.json
  tests/acceptance/test_data/templates/dynamic_aggregators_col_type_mismatch_4.json
  tests/acceptance/test_data/templates/dynamic_aggregators_same_tables_cols_result.json
  tests/acceptance/test_data/templates/dynamic_aggregators_table_mismatch_t1.json
  tests/acceptance/test_data/templates/dynamic_aggregators_table_mismatch_t2.json
  tests/acceptance/test_data/templates/expected_search_path_1.txt
  tests/acceptance/test_data/templates/expected_search_path_2.txt
  tests/acceptance/test_data/templates/expected_search_path_3.txt
  tests/acceptance/test_data/templates/expected_search_path_4.txt
  tests/acceptance/test_data/templates/expected_search_path_5.txt
  tests/acceptance/test_data/templates/expected_search_path_6.txt
  tests/acceptance/test_files/dynamic_aggregators.bats
Labels: test
