Repository turbot/steampipe, pull requests merged in 2023-09, with the labels that each got.

#3761 Rotate SSL certificates before server starts, if necessary. Closes #3599
  .github/workflows/release_cli_and_assets.yml
  .github/workflows/test.yml
  pkg/db/db_common/tls_config.go
  pkg/db/db_local/ssl.go
  pkg/db/db_local/start_services.go
  pkg/db/sslio/sslio.go
  pkg/task/runner.go
  pkg/task/ssl.go
  tests/acceptance/run.sh
  tests/acceptance/test_files/ssl.bats
Labels: bug

#3680 Adds feature for the Steampipe CLI to log to files like plugin manager and postgres. Closes #2916
  cmd/root.go
  pkg/constants/env.go
Labels: enhancement

#3784 Fixes issue where connections would get dropped in the interactive prompt. Closes #3781
  cmd/query.go
  pkg/db/db_client/db_client.go
  pkg/db/db_client/db_client_connect.go
  pkg/db/db_client/db_client_options.go
  pkg/db/db_common/client.go
  pkg/db/db_local/local_db_client.go
  pkg/initialisation/init_data.go
  pkg/interactive/interactive_client.go
  pkg/query/init_data.go
  pkg/workspace/workspace_events.go
Labels: house-keeping, interactive prompt, core

#3815 Fixes issue where Fetch and Hydrate data are not shown with timing enabled. Closes #3808
  pkg/db/db_client/db_client_execute.go
  pkg/db/db_client/scan_metadata.go
  tests/acceptance/test_files/chaos_and_query.bats
Labels: bug

#3810 Fix plugin manager shutdown. Closes #3817
  .github/workflows/test.yml
  pkg/connection/connection_state_table_updater.go
  pkg/connection/refresh_connections.go
  pkg/connection/refresh_connections_state.go
  pkg/db/db_local/create_connection.go
  pkg/db/db_local/execute.go
  pkg/pluginmanager/lifecycle.go
  pkg/pluginmanager/plugin_manager_client.go
  pkg/pluginmanager_service/plugin_manager.go
  pkg/steampipeconfig/connection_plugin.go
  pkg/steampipeconfig/connection_updates.go
  pkg/steampipeconfig/load_connection_state.go
Labels: bug, core

#3819 Fixes issue where plugin manager shutdown would stall intermittently. Closes #3818
  pkg/pluginmanager_service/plugin_manager.go
Labels: bug

#3816 Fix issue where ensureDefaultConfigFile was always overwriting default.spc. Closes #3814
  pkg/constants/db.go
  pkg/steampipeconfig/load_config.go
  tests/acceptance/test_data/source_files/default_cache_ttl_10.spc
Labels: bug, update unreleased feature

#3821 Add examples to mod commands help outputs. Closes #1817
  cmd/mod.go
Labels: enhancement, ui

#3756 Cloud and workspace flags should not be Global Flags as they are not used for all commands. Closes #3542
  cmd/check.go
  cmd/dashboard.go
  cmd/login.go
  cmd/mod.go
  cmd/query.go
  cmd/root.go
  cmd/service.go
  cmd/variable.go
  pkg/cmdconfig/builder.go
  tests/acceptance/test_data/source_files/config_tests/sp_install_dir_default/README.md
  tests/acceptance/test_data/source_files/config_tests/sp_install_dir_env/README.md
  tests/acceptance/test_data/source_files/config_tests/sp_install_dir_sample/README.md
  tests/acceptance/test_data/source_files/config_tests/workspace_tests.json
  tests/acceptance/test_data/templates/expected_plugin_help_output.txt
  tests/acceptance/test_data/templates/expected_service_help_output.txt
  tests/acceptance/test_files/config_precedence.bats
  tests/acceptance/test_files/plugin.bats
  tests/acceptance/test_files/service.bats
Labels: bug

#3840 Move db location functions into filepaths package. Closes #2122
  cmd/service.go
  pkg/db/db_local/backup.go
  pkg/db/db_local/create_connection.go
  pkg/db/db_local/install.go
  pkg/db/db_local/locations.go
  pkg/db/db_local/password.go
  pkg/db/db_local/service.go
  pkg/db/db_local/ssl.go
  pkg/db/db_local/start_services.go
  pkg/filepaths/db_path.go
  pkg/ociinstaller/fdw.go
Labels: house-keeping

#3844 Removing comment referring to unplanned issue. Closes #1301
  pkg/connection/config_map.go
  pkg/control/controlexecute/result_group.go
  pkg/error_helpers/error_and_warnings.go
  pkg/plugin/version_checker.go
Labels: house-keeping

#3859 Installs only FDW when fdw files are not installed. Closes #2040
  cmd/service.go
  pkg/db/db_local/install.go
  pkg/pluginmanager_service/plugin_manager.go
Labels: bug

#3856 Updates messaging when service is started on an unavailable port. Closes #623
  cmd/service.go
  pkg/db/db_local/start_services.go
Labels: cli output

#3862 Fixes issue where multiple 'service start' would error even on same listen params. Closes #3861
  cmd/service.go
  pkg/db/db_local/create_connection.go
  pkg/db/db_local/running_info.go
  pkg/db/db_local/start_services.go
  pkg/utils/string_slice.go
  tests/acceptance/test_files/service.bats
Labels: bug

#3869 Raises warning when pseudo resources are ignored because of named hcl resources. Closes #1328. Closes #1480
  pkg/steampipeconfig/parse/mod.go
  pkg/steampipeconfig/parse/parser.go
Labels: bug

#3880 Fixes issue where 'stdin' would get consumed even if there are arguments. Closes #3879. Closes #1985.
  cmd/query.go
  pkg/constants/db.go
  tests/acceptance/run.sh
  tests/acceptance/test_files/cache.bats
  tests/acceptance/test_files/search_path.bats
Labels: bug

#3779 Tweaks to export behaviour in 'check'. Closes #3777
  cmd/check.go
  pkg/control/controldisplay/formatter_template.go
  pkg/control/controldisplay/snapshot.go
  pkg/control/controldisplay/templates/json/output.tmpl
  pkg/control/controldisplay/templates/json/version.json
  pkg/control/controlexecute/control_run.go
  pkg/control/controlexecute/execution_tree.go
  pkg/control/controlexecute/result_group.go
  pkg/export/manager.go
  pkg/export/target.go
  pkg/steampipeconfig/modconfig/benchmark.go
  pkg/steampipeconfig/modconfig/parsed_name.go
  tests/acceptance/test_files/check.bats
Labels: house-keeping, core

#3897 Re-enable verify cache ttl works when set in database options test. Closes #3891
  pkg/db/db_local/stop_services.go
  pkg/workspace/workspace.go
  tests/acceptance/test_files/cache.bats
Labels: test

#3917 Fixes issue where cloud login is not recognised even if successful. Closes #3916
  cmd/check.go
  cmd/dashboard.go
  cmd/login.go
  cmd/query.go
  cmd/root.go
  pkg/cmdconfig/builder.go
  tests/acceptance/test_data/templates/expected_plugin_help_output.txt
  tests/acceptance/test_data/templates/expected_service_help_output.txt
Labels: bug

#3901 Fix issue where control fails with empty list as a param. Closes #2094
  pkg/steampipeconfig/modconfig/var_config/named_values.go
  pkg/type_conversion/cty_conversion.go
  tests/acceptance/run.sh
  tests/acceptance/test_data/mods/mod_with_list_param/mod.sp
  tests/acceptance/test_files/mod.bats
Labels: bug

#3924 Update help for 'steampipe plugin install'
  cmd/plugin.go
Labels: documentation

#3921 [WIP] Fixes issue where 'cloud-*' needed to be global flags. Closes #3923
  cmd/check.go
  cmd/dashboard.go
  cmd/login.go
  cmd/query.go
  cmd/root.go
  pkg/cmdconfig/builder.go
  pkg/cmdconfig/cmd_hooks.go
  pkg/cmdconfig/viper.go
  pkg/utils/pid_exists.go
  tests/acceptance/test_data/source_files/config_tests/workspace_tests.json
  tests/acceptance/test_data/templates/expected_plugin_help_output.txt
  tests/acceptance/test_data/templates/expected_service_help_output.txt
  tests/acceptance/test_files/cloud.bats
Labels: bug

#3933 Fixes issue where 20.x client would fail to connect to 21.x service in interactive. Closes #3931
  pkg/db/db_local/running_info.go
Labels: bug
