Repository turbot/steampipe, pull requests merged in 2023-05, with the labels that each got.

#3379 Fixes issue where an empty spinner is shown. Closes #3378
  pkg/statushooks/spinner.go
Labels: bug

#3396 Fixes issue where deprecation warning was not shown for using 'options.connection' in 'connection' block. Closes #3223.
  pkg/steampipeconfig/load_config.go
  pkg/steampipeconfig/parse/connection.go
  pkg/steampipeconfig/steampipeconfig.go
Labels: bug

#3425 Fixes issue where 'plugin-manager' would load the installation state and also print errors when unable to do so. Closes #3421
  cmd/plugin.go
  cmd/root.go
  pkg/installationstate/state.go
  pkg/plugin/version_checker.go
  pkg/task/runner.go
Labels: bug

#3399 Fixes issue where 'internal' would be added twice in the search_path if one is mentioned in the non default search path. Closes #3397
  pkg/db/db_client/db_client_search_path.go
  pkg/db/db_common/search_path.go
  pkg/db/db_local/search_path.go
  tests/acceptance/test_data/templates/expected_search_path_internal_schema_once_1.txt
  tests/acceptance/test_data/templates/expected_search_path_internal_schema_once_2.txt
  tests/acceptance/test_files/search_path.bats
Labels: bug

#3446 Introduces SQL functions to easily manipulate caching functionality. Closes #3442
  pkg/constants/db.go
  pkg/db/db_common/cache_control.go
  pkg/db/db_common/functions.go
Labels: enhancement

#3445 Fix issue where plugin list was returning non-0 exit code if the plugin was already installed. Closes #3444
  cmd/plugin.go
  tests/acceptance/test_files/service_and_plugin.bats
Labels: bug

#3450 Fixes issue where sometimes 0 bytes would be written to 'plugins/versions.json'. Closes #3448
  pkg/ociinstaller/versionfile/plugin_version_file.go
Labels: bug

#3454 Fixes docker build which doesn't work with new exit codes. Closes #3452
  Dockerfile
Labels: bug, devops

#3497 Fix issue where result counter spinner was not showing up in interactive when timing was enabled. Closes #3481
  pkg/db/db_client/db_client_execute.go
Labels: bug

#3491 Fix issue where steampipe completion was creating install directories. Closes #3485
  .github/workflows/release_cli_and_assets.yml
  .github/workflows/test.yml
  cmd/root.go
  tests/acceptance/test_files/brew.bats
Labels: bug
