Repository turbot/steampipe, pull requests merged in 2023-08, with the labels that each got.

#3719 Split service and plugin acceptance tests
  .github/workflows/release_cli_and_assets.yml
  .github/workflows/test.yml
  tests/acceptance/test_files/plugin.bats
  tests/acceptance/test_files/service.bats
Labels: test

#3710 Fixes issue where '.inspect' would panic for long column descriptions. Closes #3709
  pkg/control/controldisplay/formatter_text.go
  pkg/display/display.go
Labels: bug

#3714 Fix issue where interactive prompt exits/crashes when the code panics. Closes #3713
  pkg/interactive/interactive_client.go
  pkg/utils/interactive_exit_status.go
Labels: bug

#3718 Update BuildFullResourceName to validate for non empty arguments. Closes #3601
  cmd/check.go
  pkg/dashboard/dashboardexecute/dashboard_execution_tree.go
  pkg/dashboard/dashboardexecute/snapshot.go
  pkg/steampipeconfig/modconfig/dashboard.go
  pkg/steampipeconfig/modconfig/dashboard_table.go
  pkg/steampipeconfig/modconfig/parsed_name.go
Labels: house-keeping

#3707 Fixes issue with the plugin manager where multi line logs were not coming up. Closes #3706. Closes #3678.
  cmd/plugin_manager.go
  go.mod
  go.sum
Labels: bug

#3705 Update config precedence tests. Closes #3704
  .github/workflows/release_cli_and_assets.yml
  .github/workflows/test.yml
  tests/acceptance/test_files/config_precedence.bats
Labels: house-keeping, test

#3735 Fixes issue where refresh connections was not running when service was already running. Closes #3734
  pkg/db/db_local/start_services.go
  pkg/pluginmanager_service/plugin_manager.go
  tests/acceptance/test_files/dynamic_aggregators.bats
  tests/acceptance/test_files/dynamic_schema.bats
Labels: bug

#3745 Fixes issue where db connections are not closed after sending postgres notification. Closes #3744
  pkg/connection/refresh_connections_state.go
Labels: bug

#3754 Add support for mixed case schema names. Closes #3753
  pkg/db/db_local/sql_clone.go
  tests/acceptance/test_data/source_files/chaos_case_sensitivity.spc
  tests/acceptance/test_files/schema_cloning.bats
Labels: bug

#3770 Upgrades go version to 1.21. Closes #3763
  .github/workflows/release_cli_and_assets.yml
  .github/workflows/test.yml
  go.mod
  pkg/constants/db.go
  tests/acceptance/test_files/dashboard.bats
Labels: house-keeping, dependencies, core

#3767 Steampipe should return file not found as error when the input file does not exist. Closes #1752
  pkg/workspace/workspace_queries.go
  tests/acceptance/test_files/chaos_and_query.bats
  tests/acceptance/test_files/schema_cloning.bats
Labels: bug

#3687 Defined application names for all database sessions. Closes #3600
  cmd/plugin.go
  cmd/plugin_manager.go
  design/steampipe_service_db_connections.md
  go.sum
  pkg/connection/refresh_connections_state.go
  pkg/connection_sync/wait_for_search_path.go
  pkg/constants/app.go
  pkg/constants/db.go
  pkg/constants/runtime/execution_id.go
  pkg/db/db_client/db_client.go
  pkg/db/db_client/db_client_connect.go
  pkg/db/db_client/db_client_execute.go
  pkg/db/db_client/db_client_execute_retry.go
  pkg/db/db_client/db_client_search_path.go
  pkg/db/db_client/db_client_session.go
  pkg/db/db_client/scan_metadata.go
  pkg/db/db_common/appname.go
  pkg/db/db_common/cache_control.go
  pkg/db/db_common/client.go
  pkg/db/db_common/db_session.go
  pkg/db/db_common/schema.go
  pkg/db/db_common/search_path.go
  pkg/db/db_common/session_system.go
  pkg/db/db_local/create_connection.go
  pkg/db/db_local/execute.go
  pkg/db/db_local/install.go
  pkg/db/db_local/install_test.go
  pkg/db/db_local/introspection_tables.go
  pkg/db/db_local/stop_services.go
  pkg/interactive/interactive_client.go
  pkg/interactive/interactive_client_autocomplete.go
  pkg/pluginmanager_service/plugin_manager.go
  pkg/serversettings/load.go
  pkg/steampipeconfig/load_connection_state.go
  pkg/workspace/session_data.go
Labels: enhancement

#3758 Fixes issue where temporary tables are lost in the middle of a long running interactive session. Closes #3543
  pkg/db/db_client/db_client.go
  pkg/db/db_client/db_client_session.go
  pkg/db/db_common/client.go
  pkg/db/db_common/db_session.go
  pkg/interactive/interactive_client_init.go
Labels: bug, core

#3782 Steampipe should not validate locally installed plugins when connecting to remote steampipe database. Closes #3516
  pkg/initialisation/init_data.go
Labels: bug

#3783 Fixes issue where steampipe was returning index out of range error when children property of a benchmark had an invalid name. Closes #3563
  pkg/steampipeconfig/modconfig/parsed_property_path.go
  pkg/steampipeconfig/modconfig/parsed_property_path_test.go
Labels: bug
