Repository turbot/steampipe, pull requests merged in 2023-06, with the labels that each got.

#3520 Add plugin list acceptance tests. Closes #3519
  pkg/cmdconfig/viper.go
  pkg/constants/args.go
  pkg/constants/env.go
  pkg/control/controldisplay/formatter_text.go
  pkg/display/display.go
  pkg/utils/range.go
  tests/acceptance/test_data/templates/expected_plugin_list_table.txt
  tests/acceptance/test_data/templates/expected_plugin_list_table_with_missing_plugins.txt
  tests/acceptance/test_files/check.bats
  tests/acceptance/test_files/service_and_plugin.bats
Labels: test

#3538 Fixes issue where prefixing a 'v' on a version stream during plugin install would come back with 'not found'. Closes #3513
  pkg/ociinstaller/imageref.go
  pkg/ociinstaller/imageref_test.go
  tests/acceptance/test_files/service_and_plugin.bats
Labels: bug

#3534 Re-enable tests to verify unmet dependencies behaviour for dashboard. Closes #3359
  tests/acceptance/test_data/bad_mod_with_dep_mod_version_require_not_met/README.md
  tests/acceptance/test_data/bad_mod_with_dep_mod_version_require_not_met/dashboard.sp
  tests/acceptance/test_data/bad_mod_with_plugin_require_not_met/README.md
  tests/acceptance/test_data/bad_mod_with_plugin_require_not_met/dashboard.sp
  tests/acceptance/test_data/bad_mod_with_sp_version_require_not_met/README.md
  tests/acceptance/test_data/bad_mod_with_sp_version_require_not_met/dashboard.sp
  tests/acceptance/test_files/mod_require.bats
Labels: test

#3530 Fixes issue where OS specific metadata directories were being considered as check templates. Closes #3523
  go.mod
  go.sum
  pkg/control/controldisplay/format_resolver.go
  pkg/initialisation/init_data.go
Labels: bug

#3473 Add Linux ARM tests in Steampipe Release (CLI and Assets) workflow. Closes #3468
  .github/workflows/release_cli_and_assets.yml
  tests/acceptance/run-linux-arm.sh
  tests/acceptance/run-local.sh
  tests/acceptance/test_data/dependent_mod_with_legacy_lock/.mod.cache.json
  tests/acceptance/test_data/dependent_mod_with_legacy_lock/.steampipe/mods/github.com/pskrbasu/steampipe-mod-m1@v4.0/.gitignore
  tests/acceptance/test_data/dependent_mod_with_legacy_lock/.steampipe/mods/github.com/pskrbasu/steampipe-mod-m1@v4.0/dashboard.sp
  tests/acceptance/test_data/dependent_mod_with_legacy_lock/.steampipe/mods/github.com/pskrbasu/steampipe-mod-m1@v4.0/mod.sp
  tests/acceptance/test_data/dependent_mod_with_legacy_lock/.steampipe/mods/github.com/pskrbasu/steampipe-mod-m1@v4.0/query.sp
  tests/acceptance/test_data/dependent_mod_with_legacy_lock/dashboard.sp
  tests/acceptance/test_data/dependent_mod_with_legacy_lock/mod.sp
  tests/acceptance/test_files/chaos_and_query.bats
  tests/acceptance/test_files/migration.bats
  tests/acceptance/test_files/schema_cloning.bats
  tests/acceptance/test_files/search_path.bats
Labels: test, github_actions

#3465 Updated sample config file behaviour as per the proposed changes. Closes #3431
  pkg/constants/default_options.go
  pkg/constants/default_workspaces.go
  pkg/steampipeconfig/load_config.go
  pkg/steampipeconfig/workspace_profile_loader.go
  pkg/utils/file.go
Labels: enhancement

#3524 Fixes issue when steampipe fails to startup if data files could not be migrated. Closes #3518
  cmd/root.go
  pkg/migrate/migrate.go
  pkg/ociinstaller/versionfile/plugin_version_file.go
Labels: bug

#3503 Fixes issue where blank dimension values are leaving extra spaces in 'table' rendering. Closes #3474
  pkg/control/controldisplay/dimensions.go
  tests/acceptance/run.sh
  tests/acceptance/test_data/mod_with_blank_dimension_value/control.sp
  tests/acceptance/test_data/mod_with_blank_dimension_value/mod.sp
  tests/acceptance/test_data/mod_with_blank_dimension_value/query.sp
  tests/acceptance/test_data/templates/expected_blank_dimension.txt
  tests/acceptance/test_files/check.bats
Labels: bug

#3555 Fixes test where an old env var was being used for defining width in non-graphic terminals. Closes #3554
  tests/acceptance/test_files/check.bats
Labels: test

#3560 Fixes issue where timing is not shown in interactive prompt even if .timing is on. Closes #3557
  pkg/display/display_options.go
Labels: bug

#3567 Fixes issue where 'plugin list' hangs if there are connections with 'import_schema = "disabled"'. Closes #3561
  pkg/plugin/actions.go
  pkg/steampipeconfig/connection_state.go
  pkg/steampipeconfig/connection_state_map.go
  pkg/steampipeconfig/modconfig/connection.go
Labels: bug

#3569 Add test for plugin list with disabled connection. Closes #3561
  cmd/plugin.go
  cmd/root.go
  pkg/statushooks/null_hooks.go
  pkg/steampipeconfig/connection_state_map.go
  pkg/steampipeconfig/modconfig/connection.go
  tests/acceptance/run.sh
  tests/acceptance/test_data/source_files/chaos_conn_import_disabled.spc
  tests/acceptance/test_files/dynamic_aggregators.bats
  tests/acceptance/test_files/dynamic_schema.bats
  tests/acceptance/test_files/service_and_plugin.bats
Labels: test

#3592 Fixes issue where exporting check all yields a badly formatted filename. Closes #3591
  cmd/check.go
  pkg/steampipeconfig/modconfig/parsed_name.go
Labels: bug

#3472 Adds 'steampipe_server_settings' table populated with server settings data during service startup. Closes #3462
  .github/workflows/release_cli_and_assets.yml
  .github/workflows/test.yml
  pkg/constants/db.go
  pkg/control/controldisplay/result_columns.go
  pkg/db/db_client/db_client.go
  pkg/db/db_client/db_client_search_path.go
  pkg/db/db_common/client.go
  pkg/db/db_common/server_settings.go
  pkg/db/db_local/execute.go
  pkg/db/db_local/server_settings.go
  pkg/db/db_local/start_services.go
  pkg/serversettings/load.go
  pkg/serversettings/setup.go
  tests/acceptance/test_files/service.bats
  tests/acceptance/test_files/settings.bats
Labels: enhancement

#3527 Integrate golangci-lint into automated testing and release. Closes #1336
  .github/workflows/test.yml
  .golangci.yml
Labels: house-keeping

#3613 Fixes issue where connection state fails to load when connecting to pre-0.20.7 service. Closes #3612
  pkg/connection_state/connection_state_table_sql.go
  pkg/interactive/interactive_client.go
  pkg/steampipeconfig/load_connection_state.go
Labels: bug

#3631 Fixes issue where interactive prompt autocomplete dropdown was showing connections in error. Closes #3628
  pkg/interactive/interactive_client_autocomplete.go
  pkg/steampipeconfig/connection_state.go
Labels: bug

#3494 Creates 'version.json' in each plugin directory. Closes #3492
  .github/workflows/test.yml
  cmd/plugin.go
  cmd/root.go
  pkg/db/db_client/db_client.go
  pkg/ociinstaller/plugin.go
  pkg/ociinstaller/versionfile/db_version_file.go
  pkg/ociinstaller/versionfile/installed_version.go
  pkg/ociinstaller/versionfile/legacy_version_file.go
  pkg/ociinstaller/versionfile/plugin_version_file.go
  pkg/ociinstaller/versionfile/plugin_version_file_test.go
  pkg/plugin/actions.go
  tests/acceptance/test_files/cloud.bats
  tests/acceptance/test_files/service_and_plugin.bats
Labels: enhancement
