Repository turbot/steampipe, pull requests merged in 2023-07, with the labels that each got.

#3479 Adds feature where type '.cache' in interactive shows the current value of cache. Closes #2439
  pkg/interactive/interactive_client.go
  pkg/interactive/interactive_client_autocomplete.go
  pkg/interactive/interactive_client_autocomplete_legacy.go
  pkg/interactive/interactive_client_init.go
  pkg/interactive/metaquery/definitions.go
  pkg/interactive/metaquery/handler_cache.go
  pkg/interactive/metaquery/handler_inspect.go
Labels: enhancement

#3595 Fixes issue where 'service start' is not listening on 'network' by default. Closes #3593
  cmd/dashboard.go
  cmd/service.go
  pkg/cmdconfig/viper.go
  pkg/db/db_local/local_db_client.go
  pkg/db/db_local/running_info.go
  pkg/db/db_local/start_services.go
  pkg/utils/net.go
  pkg/utils/semaphore.go
  tests/acceptance/test_files/service.bats
Labels: bug, update unreleased feature

#3658 Add acceptance tests to verify steampipe db, fdw, plugins installation from registry. Closes #3656
  .github/workflows/release_cli_and_assets.yml
  .github/workflows/test.yml
  tests/acceptance/test_files/installation.bats
Labels: test

#3666 Move ErrorAndWarnings to error_helpers. Closes #3653
  cmd/plugin.go
  cmd/root.go
  pkg/db/db_common/acquire_session_result.go
  pkg/db/db_local/local_db_client.go
  pkg/db/db_local/start_services.go
  pkg/error_helpers/error_and_warnings.go
  pkg/initialisation/init_data.go
  pkg/steampipeconfig/load_config.go
  pkg/steampipeconfig/load_mod.go
  pkg/steampipeconfig/load_mod_variables.go
  pkg/steampipeconfig/parse/mod.go
  pkg/steampipeconfig/refresh_connections_result.go
  pkg/steampipeconfig/steampipeconfig.go
  pkg/workspace/load_workspace.go
  pkg/workspace/workspace.go
  pkg/workspace/workspace_events.go
Labels: house-keeping

#3671 Fixes issue where CAPITAL arguments to '.cache' meta command were not getting recognised. Closes #3670
  pkg/interactive/metaquery/handler_cache.go
Labels: bug

#3648 Validates workspace profile cache settings. Closes #3646
  pkg/db/db_client/db_client_execute_retry.go
  pkg/db/db_common/cache_settings.go
  pkg/error_helpers/error_and_warnings.go
  pkg/error_helpers/errors.go
  pkg/initialisation/init_data.go
  pkg/interactive/metaquery/definitions.go
  pkg/interactive/metaquery/handler_cache.go
  pkg/interactive/metaquery/validators.go
  pkg/steampipeconfig/connection_updates.go
  tests/acceptance/test_data/source_files/chaos_no_options.spc
  tests/acceptance/test_data/source_files/chaos_ttl_options.spc
  tests/acceptance/test_data/source_files/default_cache_ttl_10.spc
  tests/acceptance/test_data/source_files/workspace_cache_ttl.spc
  tests/acceptance/test_files/cache.bats
Labels: enhancement

#3686 Fixes issue where dashboard port in `options`.`dashboard`. Closes #3685
  pkg/steampipeconfig/steampipeconfig.go
Labels: bug

#3673 Removes deprecated 'workspace-chdir' flag. Closes #3658
  cmd/root.go
  pkg/constants/args.go
  tests/acceptance/test_files/service_and_plugin.bats
Labels: house-keeping

#3688 Fixes issue where using a bad workspace-database with a valid token gives invalid token as the error. Closes #3610
  pkg/cloud/cloud_metadata.go
  pkg/error_helpers/cloud.go
Labels: bug

#3689 Remove migration and backward compatibility of data files. Closes #3517
  cmd/root.go
  pkg/installationstate/state.go
  pkg/migrate/migrate.go
  pkg/ociinstaller/versionfile/db_version_file.go
  pkg/ociinstaller/versionfile/installed_version.go
  pkg/ociinstaller/versionfile/plugin_version_file.go
Labels: migration

#3663 Steampipe commands should bypass plugin requirement check if installed plugin is local. Closes #3643
  cmd/plugin.go
  pkg/db/db_common/acquire_session_result.go
  pkg/db/db_local/column_tag.go
  pkg/db/db_local/introspection_tables.go
  pkg/initialisation/init_data.go
  pkg/modinstaller/mod_installer.go
  pkg/plugin/actions.go
  pkg/plugin/installed.go
  pkg/steampipeconfig/modconfig/mod.go
  pkg/steampipeconfig/modconfig/plugin_version_string.go
  pkg/steampipeconfig/modconfig/require.go
  pkg/steampipeconfig/plugin_remove.go
  pkg/steampipeconfig/refresh_connections_result.go
  pkg/workspace/session_data.go
  pkg/workspace/workspace_require.go
  tests/acceptance/test_files/mod_require.bats
  tests/acceptance/test_files/service_and_plugin.bats
Labels: bug

#3701 Fix installation.bats tests and increase BATS_TIMEOUT for service tests
  .github/workflows/release_cli_and_assets.yml
  tests/acceptance/test_files/installation.bats
  tests/acceptance/test_files/service.bats
  tests/acceptance/test_files/service_and_plugin.bats
Labels: test
